=== publishing-platform/publishing-api/content_schemas/dist/formats/news_article/frontend/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "required": [
    "base_path",
    "content_id",
    "description",
    "details",
    "document_type",
    "links",
    "public_updated_at",
    "schema_name",
    "title",
    "updated_at"
  ],
  "additionalProperties": false,
  "properties": {
    "base_path": {
      "$ref": "#/definitions/absolute_path"
    },
    "content_id": {
      "$ref": "#/definitions/guid"
    },
    "description": {
      "$ref": "#/definitions/description_optional"
    },
    "details": {
      "$ref": "#/definitions/details"
    },
    "document_type": {
      "type": "string",
      "enum": [
        "press_release",
        "news_story"
      ]
    },
    "first_published_at": {
      "anyOf": [
        {
          "$ref": "#/definitions/first_published_at"
        },
        {
          "type": "null"
        }
      ]
    },
    "links": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "children": {
          "description": "Link type automatically added by Publishing API",
          "$ref": "#/definitions/frontend_links_with_base_path"
        },
        "parent": {
          "description": "The parent content item.",
          "$ref": "#/definitions/frontend_links_with_base_path",
          "maxItems": 1
        },
        "primary_publishing_organisation": {
          "description": "The organisation that published the page.",
          "$ref": "#/definitions/frontend_links_with_base_path",
          "maxItems": 1
        }
      }
    },
    "phase": {
      "description": "The service design phase of this content item",
      "type": "string",
      "enum": [
        "alpha",
        "beta",
        "live"
      ]
    },
    "public_updated_at": {
      "anyOf": [
        {
          "$ref": "#/definitions/public_updated_at"
        },
        {
          "type": "null"
        }
      ]
    },
    "publishing_app": {
      "$ref": "#/definitions/publishing_app_name"
    },
    "publishing_request_id": {
      "$ref": "#/definitions/publishing_request_id"
    },
    "rendering_app": {
      "$ref": "#/definitions/rendering_app"
    },
    "schema_name": {
      "type": "string",
      "enum": [
        "news_article"
      ]
    },
    "title": {
      "$ref": "#/definitions/title"
    },
    "updated_at": {
      "type": "string",
      "format": "date-time"
    },
    "withdrawn_notice": {
      "$ref": "#/definitions/withdrawn_notice"
    }
  },
  "definitions": {
    "description": {
      "type": "string"
    },
    "absolute_path": {
      "description": "A path only. Query string and/or fragment are not allowed.",
      "type": "string",
      "pattern": "^/(([a-zA-Z0-9._~!$&'()*+,;=:@-]|%[0-9a-fA-F]{2})+(/([a-zA-Z0-9._~!$&'()*+,;=:@-]|%[0-9a-fA-F]{2})*)*)?$"
    },
    "body_html_and_markdown": {
      "description": "The main content provided as HTML with the markdown markdown it's rendered from",
      "anyOf": [
        {
          "type": "string"
        }
      ]
    },
    "change_history": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "public_timestamp",
          "note"
        ],
        "additionalProperties": false,
        "properties": {
          "note": {
            "description": "A summary of the change",
            "type": "string"
          },
          "public_timestamp": {
            "type": "string",
            "format": "date-time"
          }
        }
      }
    },
    "description_optional": {
      "anyOf": [
        {
          "$ref": "#/definitions/description"
        },
        {
          "type": "null"
        }
      ]
    },
    "details": {
      "type": "object",
      "required": [
        "body"
      ],
      "additionalProperties": false,
      "properties": {
        "attachments": {
          "description": "An ordered list of asset links",
          "type": "array",
          "items": {
            "$ref": "#/definitions/file_attachment_asset"
          }
        },
        "body": {
          "$ref": "#/definitions/body_html_and_markdown"
        },
        "change_history": {
          "$ref": "#/definitions/change_history"
        },
        "image": {
          "$ref": "#/definitions/image_asset"
        }
      }
    },
    "file_attachment_asset": {
      "type": "object",
      "required": [
        "attachment_type",
        "content_type",
        "id",
        "url"
      ],
      "additionalProperties": false,
      "properties": {
        "accessible": {
          "type": "boolean"
        },
        "alternative_format_contact_email": {
          "type": "string"
        },
        "attachment_type": {
          "type": "string",
          "enum": [
            "file"
          ]
        },
        "content_type": {
          "type": "string"
        },
        "file_size": {
          "type": "integer"
        },
        "filename": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "number_of_pages": {
          "type": "integer"
        },
        "title": {
          "type": "string"
        },
        "url": {
          "type": "string",
          "format": "uri"
        }
      }
    },
    "first_published_at": {
      "description": "The date the content was first published.  Automatically determined by the publishing-api, unless overridden by the publishing application.",
      "type": "string",
      "format": "date-time"
    },
    "frontend_links_with_base_path": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "base_path",
          "content_id",
          "title"
        ],
        "additionalProperties": true,
        "properties": {
          "api_path": {
            "$ref": "#/definitions/absolute_path"
          },
          "base_path": {
            "$ref": "#/definitions/absolute_path"
          },
          "content_id": {
            "$ref": "#/definitions/guid"
          },
          "document_type": {
            "type": "string"
          },
          "links": {
            "type": "object",
            "patternProperties": {
              "^[a-z_]+$": {
                "$ref": "#/definitions/frontend_links_with_base_path"
              }
            }
          },
          "public_updated_at": {
            "oneOf": [
              {
                "$ref": "#/definitions/public_updated_at"
              },
              {
                "type": "null"
              }
            ]
          },
          "schema_name": {
            "type": "string"
          },
          "title": {
            "type": "string"
          }
        }
      }
    },
    "guid": {
      "type": "string",
      "pattern": "^[a-f0-9]{8}-[a-f0-9]{4}-[1-5][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$"
    },
    "image_asset": {
      "type": "object",
      "required": [
        "url"
      ],
      "additionalProperties": false,
      "properties": {
        "alt_text": {
          "type": "string"
        },
        "caption": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "credit": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "high_resolution_url": {
          "description": "URL to a high resolution version of the image, for use by third parties such as Twitter, Facebook or Slack. Used by the machine readable metadata component. Don't use this on user-facing web pages, as it might be very large.",
          "type": "string",
          "format": "uri"
        },
        "medium_resolution_url": {
          "description": "URL to a medium resolution version of the image, for use by devices that have high pixel density such as iphone.",
          "type": "string",
          "format": "uri"
        },
        "url": {
          "description": "URL to the image. The image should be in a suitable resolution for display on the page.",
          "type": "string",
          "format": "uri"
        }
      }
    },
    "public_updated_at": {
      "description": "When the content was last significantly changed (a major update). Shown to users.  Automatically determined by the publishing-api, unless overridden by the publishing application.",
      "type": "string",
      "format": "date-time"
    },
    "publishing_app_name": {
      "description": "The application that published this item.",
      "type": "string",
      "enum": [
        "content-publisher",
        "organisations-publisher",
        "publisher",
        "publishing-api"
      ]
    },
    "publishing_request_id": {
      "description": "A unique identifier used to track publishing requests to rendered content",
      "oneOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ]
    },
    "rendering_app": {
      "description": "The application that renders this item.",
      "type": "string",
      "enum": [
        "collections-frontend",
        "content-store",
        "frontend"
      ]
    },
    "title": {
      "type": "string"
    },
    "withdrawn_notice": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "explanation": {
          "type": "string"
        },
        "withdrawn_at": {
          "format": "date-time"
        }
      }
    }
  }
}

=== publishing-platform/publishing-api/content_schemas/examples/news/frontend/press_release.json
{
  "base_path": "/news/modern-life-responsible-for-worrying-health-in-middle-aged",
  "content_id": "55f26cf1-3b96-452c-a7d3-ee0b65db9d8b",
  "description": "Helping middle age people live more healthily by asking ‘How are you?’ and providing free support and tools.",
  "details": {
    "attachments": [],
    "body": "\u003Cp\u003EEight out of 10 of the middle aged either weigh too much, drink too much or don’t exercise enough.\u003C/p\u003E\n",
    "change_history": [
      {
        "note": "First published.",
        "public_timestamp": "2026-02-25T21:29:46.766+00:00"
      }
    ],
    "image": {
      "alt_text": "How are you billboard",
      "url": "https://assets.dev.publishing-platform.co.uk/testing.jpg"
    }
  },
  "document_type": "press_release",
  "first_published_at": null,
  "links": {
    "primary_publishing_organisation": [
      {
        "api_path": "/api/content/organisations/digital-services",
        "api_url": "http://draft-www.dev.publishing-platform.co.uk/api/content/organisations/digital-services",
        "base_path": "/organisations/digital-services",
        "content_id": "af07d5a5-df63-4ddc-9383-6a666845ebe9",
        "details": {
          "abbreviation": "DS",
          "status": "live"
        },
        "document_type": "organisation",
        "links": {

        },
        "schema_name": "organisation",
        "title": "Digital Services",
        "web_url": "http://draft-www.dev.publishing-platform.co.uk/organisations/digital-services",
        "withdrawn": false
      }
    ]
  },
  "phase": "live",
  "public_updated_at": "2026-02-25T21:29:46Z",
  "publishing_app": "content-publisher",
  "publishing_request_id": null,
  "rendering_app": "frontend",
  "schema_name": "news_article",
  "title": "Modern life responsible for ‘worrying’ health in middle aged",
  "updated_at": "2026-03-11T09:07:01Z",
  "withdrawn_notice": {

  }
}
