=== publishing-platform/publishing-api/content_schemas/dist/formats/redirect/frontend/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "required": [
    "base_path",
    "content_id",
    "description",
    "details",
    "document_type",
    "links",
    "public_updated_at",
    "schema_name",
    "title",
    "updated_at"
  ],
  "additionalProperties": false,
  "properties": {
    "base_path": {
      "$ref": "#/definitions/absolute_path"
    },
    "content_id": {
      "$ref": "#/definitions/guid_optional"
    },
    "description": {
      "type": "null"
    },
    "details": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
      }
    },
    "document_type": {
      "type": "string",
      "enum": [
        "redirect"
      ]
    },
    "first_published_at": {
      "anyOf": [
        {
          "$ref": "#/definitions/first_published_at"
        },
        {
          "type": "null"
        }
      ]
    },
    "links": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "children": {
          "description": "Link type automatically added by Publishing API",
          "$ref": "#/definitions/frontend_links_with_base_path"
        }
      }
    },
    "phase": {
      "description": "The service design phase of this content item",
      "type": "string",
      "enum": [
        "alpha",
        "beta",
        "live"
      ]
    },
    "public_updated_at": {
      "anyOf": [
        {
          "$ref": "#/definitions/public_updated_at"
        },
        {
          "type": "null"
        }
      ]
    },
    "publishing_app": {
      "$ref": "#/definitions/publishing_app_name"
    },
    "publishing_request_id": {
      "$ref": "#/definitions/publishing_request_id"
    },
    "redirects": {
      "$ref": "#/definitions/redirects"
    },
    "rendering_app": {
      "type": "null"
    },
    "schema_name": {
      "type": "string",
      "enum": [
        "redirect"
      ]
    },
    "title": {
      "type": "null"
    },
    "updated_at": {
      "type": "string",
      "format": "date-time"
    },
    "withdrawn_notice": {
      "$ref": "#/definitions/withdrawn_notice"
    }
  },
  "definitions": {
    "absolute_path": {
      "description": "A path only. Query string and/or fragment are not allowed.",
      "type": "string",
      "pattern": "^/(([a-zA-Z0-9._~!$&'()*+,;=:@-]|%[0-9a-fA-F]{2})+(/([a-zA-Z0-9._~!$&'()*+,;=:@-]|%[0-9a-fA-F]{2})*)*)?$"
    },
    "first_published_at": {
      "description": "The date the content was first published.  Automatically determined by the publishing-api, unless overridden by the publishing application.",
      "type": "string",
      "format": "date-time"
    },
    "frontend_links_with_base_path": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "base_path",
          "content_id",
          "title"
        ],
        "additionalProperties": true,
        "properties": {
          "api_path": {
            "$ref": "#/definitions/absolute_path"
          },
          "base_path": {
            "$ref": "#/definitions/absolute_path"
          },
          "content_id": {
            "$ref": "#/definitions/guid"
          },
          "document_type": {
            "type": "string"
          },
          "links": {
            "type": "object",
            "patternProperties": {
              "^[a-z_]+$": {
                "$ref": "#/definitions/frontend_links_with_base_path"
              }
            }
          },
          "public_updated_at": {
            "oneOf": [
              {
                "$ref": "#/definitions/public_updated_at"
              },
              {
                "type": "null"
              }
            ]
          },
          "schema_name": {
            "type": "string"
          },
          "title": {
            "type": "string"
          }
        }
      }
    },
    "guid": {
      "type": "string",
      "pattern": "^[a-f0-9]{8}-[a-f0-9]{4}-[1-5][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$"
    },
    "guid_optional": {
      "anyOf": [
        {
          "$ref": "#/definitions/guid"
        },
        {
          "type": "null"
        }
      ]
    },
    "public_updated_at": {
      "description": "When the content was last significantly changed (a major update). Shown to users.  Automatically determined by the publishing-api, unless overridden by the publishing application.",
      "type": "string",
      "format": "date-time"
    },
    "publishing_app_name": {
      "description": "The application that published this item.",
      "type": "string",
      "enum": [
        "organisations-publisher",
        "publisher"
      ]
    },
    "publishing_request_id": {
      "description": "A unique identifier used to track publishing requests to rendered content",
      "oneOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ]
    },
    "redirect_route": {
      "type": "object",
      "required": [
        "path",
        "type",
        "destination"
      ],
      "additionalProperties": false,
      "properties": {
        "destination": {
          "type": "string",
          "format": "uri"
        },
        "path": {
          "$ref": "#/definitions/absolute_path"
        },
        "segments_mode": {
          "description": "For prefix redirects, preserve or ignore the rest of the fullpath. For exact, preserve or ignore the querystring.",
          "enum": [
            "preserve",
            "ignore"
          ]
        },
        "type": {
          "enum": [
            "prefix",
            "exact"
          ]
        }
      }
    },
    "redirects": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/redirect_route"
      },
      "minItems": 1
    },
    "withdrawn_notice": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "explanation": {
          "type": "string"
        },
        "withdrawn_at": {
          "format": "date-time"
        }
      }
    }
  }
}

=== publishing-platform/publishing-api/content_schemas/examples/redirect/frontend/redirect.json
{
  "base_path": "/test-redirect",
  "content_id": null,
  "description": null,
  "details": {

  },
  "document_type": "redirect",
  "first_published_at": "2024-08-28T16:21:11Z",
  "links": {

  },
  "phase": "live",
  "public_updated_at": "2024-08-28T16:21:11Z",
  "publishing_app": "publisher",
  "publishing_request_id": "30559-1487239320.697-62.232.86.100-23977",
  "redirects": [
    {
      "destination": "/test-redirected?query=answer#fragment",
      "path": "/test-redirect",
      "type": "exact"
    }
  ],
  "rendering_app": null,
  "schema_name": "redirect",
  "title": null,
  "updated_at": "2024-08-28T16:21:11Z",
  "withdrawn_notice": {

  }
}
