=== publishing-platform/publishing-api/content_schemas/dist/formats/special_route/frontend/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "required": [
    "base_path",
    "content_id",
    "description",
    "details",
    "document_type",
    "links",
    "public_updated_at",
    "schema_name",
    "title",
    "updated_at"
  ],
  "additionalProperties": false,
  "properties": {
    "base_path": {
      "$ref": "#/definitions/absolute_path"
    },
    "content_id": {
      "$ref": "#/definitions/guid"
    },
    "description": {
      "$ref": "#/definitions/description_optional"
    },
    "details": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
      }
    },
    "document_type": {
      "type": "string",
      "enum": [
        "special_route"
      ]
    },
    "first_published_at": {
      "anyOf": [
        {
          "$ref": "#/definitions/first_published_at"
        },
        {
          "type": "null"
        }
      ]
    },
    "links": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "children": {
          "description": "Link type automatically added by Publishing API",
          "$ref": "#/definitions/frontend_links_with_base_path"
        },
        "parent": {
          "description": "The parent content item.",
          "$ref": "#/definitions/frontend_links_with_base_path",
          "maxItems": 1
        },
        "primary_publishing_organisation": {
          "description": "The organisation that published the page.",
          "$ref": "#/definitions/frontend_links_with_base_path",
          "maxItems": 1
        }
      }
    },
    "phase": {
      "description": "The service design phase of this content item",
      "type": "string",
      "enum": [
        "alpha",
        "beta",
        "live"
      ]
    },
    "public_updated_at": {
      "anyOf": [
        {
          "$ref": "#/definitions/public_updated_at"
        },
        {
          "type": "null"
        }
      ]
    },
    "publishing_app": {
      "$ref": "#/definitions/publishing_app_name"
    },
    "publishing_request_id": {
      "$ref": "#/definitions/publishing_request_id"
    },
    "rendering_app": {
      "$ref": "#/definitions/rendering_app_optional"
    },
    "schema_name": {
      "type": "string",
      "enum": [
        "special_route"
      ]
    },
    "title": {
      "$ref": "#/definitions/title_optional"
    },
    "updated_at": {
      "type": "string",
      "format": "date-time"
    },
    "withdrawn_notice": {
      "$ref": "#/definitions/withdrawn_notice"
    }
  },
  "definitions": {
    "description": {
      "type": "string"
    },
    "absolute_path": {
      "description": "A path only. Query string and/or fragment are not allowed.",
      "type": "string",
      "pattern": "^/(([a-zA-Z0-9._~!$&'()*+,;=:@-]|%[0-9a-fA-F]{2})+(/([a-zA-Z0-9._~!$&'()*+,;=:@-]|%[0-9a-fA-F]{2})*)*)?$"
    },
    "description_optional": {
      "anyOf": [
        {
          "$ref": "#/definitions/description"
        },
        {
          "type": "null"
        }
      ]
    },
    "first_published_at": {
      "description": "The date the content was first published.  Automatically determined by the publishing-api, unless overridden by the publishing application.",
      "type": "string",
      "format": "date-time"
    },
    "frontend_links_with_base_path": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "base_path",
          "content_id",
          "title"
        ],
        "additionalProperties": true,
        "properties": {
          "api_path": {
            "$ref": "#/definitions/absolute_path"
          },
          "base_path": {
            "$ref": "#/definitions/absolute_path"
          },
          "content_id": {
            "$ref": "#/definitions/guid"
          },
          "document_type": {
            "type": "string"
          },
          "links": {
            "type": "object",
            "patternProperties": {
              "^[a-z_]+$": {
                "$ref": "#/definitions/frontend_links_with_base_path"
              }
            }
          },
          "public_updated_at": {
            "oneOf": [
              {
                "$ref": "#/definitions/public_updated_at"
              },
              {
                "type": "null"
              }
            ]
          },
          "schema_name": {
            "type": "string"
          },
          "title": {
            "type": "string"
          }
        }
      }
    },
    "guid": {
      "type": "string",
      "pattern": "^[a-f0-9]{8}-[a-f0-9]{4}-[1-5][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$"
    },
    "public_updated_at": {
      "description": "When the content was last significantly changed (a major update). Shown to users.  Automatically determined by the publishing-api, unless overridden by the publishing application.",
      "type": "string",
      "format": "date-time"
    },
    "publishing_app_name": {
      "description": "The application that published this item.",
      "type": "string",
      "enum": [
        "organisations-publisher",
        "publisher",
        "publishing-api"
      ]
    },
    "publishing_request_id": {
      "description": "A unique identifier used to track publishing requests to rendered content",
      "oneOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ]
    },
    "rendering_app": {
      "description": "The application that renders this item.",
      "type": "string",
      "enum": [
        "collections-frontend",
        "content-store",
        "frontend"
      ]
    },
    "rendering_app_optional": {
      "anyOf": [
        {
          "$ref": "#/definitions/rendering_app"
        },
        {
          "type": "null"
        }
      ]
    },
    "title_optional": {
      "type": "string"
    },
    "withdrawn_notice": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "explanation": {
          "type": "string"
        },
        "withdrawn_at": {
          "format": "date-time"
        }
      }
    }
  }
}

=== publishing-platform/publishing-api/content_schemas/examples/special_route/frontend/special_route.json
{
  "base_path": "/api/content",
  "content_id": "16ca5ac1-7df5-4137-9f83-0270fcfc8bb5",
  "description": "API exposing all content on Publishing Platform.",
  "details": {

  },
  "document_type": "special_route",
  "first_published_at": "2025-02-13T22:16:40Z",
  "links": {

  },
  "phase": "live",
  "public_updated_at": "2025-02-13T13:58:11+00:00",
  "publishing_app": "publishing-api",
  "publishing_request_id": "21-1696943400.771-10.13.26.155-382",
  "rendering_app": "content-store",
  "schema_name": "special_route",
  "title": "Content API",
  "updated_at": "2025-02-13T22:16:40Z",
  "withdrawn_notice": {

  }
}
