=== publishing-platform/publishing-api/content_schemas/dist/formats/organisation/frontend/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "required": [
    "base_path",
    "content_id",
    "description",
    "details",
    "document_type",
    "links",
    "public_updated_at",
    "schema_name",
    "title",
    "updated_at"
  ],
  "additionalProperties": false,
  "properties": {
    "base_path": {
      "$ref": "#/definitions/absolute_path"
    },
    "content_id": {
      "$ref": "#/definitions/guid"
    },
    "description": {
      "$ref": "#/definitions/description_optional"
    },
    "details": {
      "$ref": "#/definitions/details"
    },
    "document_type": {
      "type": "string",
      "enum": [
        "organisation"
      ]
    },
    "first_published_at": {
      "anyOf": [
        {
          "$ref": "#/definitions/first_published_at"
        },
        {
          "type": "null"
        }
      ]
    },
    "links": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "children": {
          "description": "Link type automatically added by Publishing API",
          "$ref": "#/definitions/frontend_links_with_base_path"
        },
        "parent": {
          "description": "The parent content item.",
          "$ref": "#/definitions/frontend_links_with_base_path",
          "maxItems": 1
        },
        "primary_publishing_organisation": {
          "description": "The organisation that published the page.",
          "$ref": "#/definitions/frontend_links_with_base_path",
          "maxItems": 1
        }
      }
    },
    "phase": {
      "description": "The service design phase of this content item",
      "type": "string",
      "enum": [
        "alpha",
        "beta",
        "live"
      ]
    },
    "public_updated_at": {
      "anyOf": [
        {
          "$ref": "#/definitions/public_updated_at"
        },
        {
          "type": "null"
        }
      ]
    },
    "publishing_app": {
      "$ref": "#/definitions/publishing_app_name"
    },
    "publishing_request_id": {
      "$ref": "#/definitions/publishing_request_id"
    },
    "rendering_app": {
      "$ref": "#/definitions/rendering_app"
    },
    "schema_name": {
      "type": "string",
      "enum": [
        "organisation"
      ]
    },
    "title": {
      "$ref": "#/definitions/title"
    },
    "updated_at": {
      "type": "string",
      "format": "date-time"
    },
    "withdrawn_notice": {
      "$ref": "#/definitions/withdrawn_notice"
    }
  },
  "definitions": {
    "description": {
      "type": "string"
    },
    "absolute_path": {
      "description": "A path only. Query string and/or fragment are not allowed.",
      "type": "string",
      "pattern": "^/(([a-zA-Z0-9._~!$&'()*+,;=:@-]|%[0-9a-fA-F]{2})+(/([a-zA-Z0-9._~!$&'()*+,;=:@-]|%[0-9a-fA-F]{2})*)*)?$"
    },
    "change_history": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "public_timestamp",
          "note"
        ],
        "additionalProperties": false,
        "properties": {
          "note": {
            "description": "A summary of the change",
            "type": "string"
          },
          "public_timestamp": {
            "type": "string",
            "format": "date-time"
          }
        }
      }
    },
    "description_optional": {
      "anyOf": [
        {
          "$ref": "#/definitions/description"
        },
        {
          "type": "null"
        }
      ]
    },
    "details": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "abbreviation": {
          "description": "The organisation's abbreviation, if it has one.",
          "type": [
            "string",
            "null"
          ]
        },
        "change_history": {
          "$ref": "#/definitions/change_history"
        },
        "organisation_type": {
          "description": "The type of organisation.",
          "type": "string",
          "enum": [
            "department",
            "other"
          ]
        },
        "status": {
          "type": "string",
          "enum": [
            "closed",
            "live"
          ]
        }
      }
    },
    "first_published_at": {
      "description": "The date the content was first published.  Automatically determined by the publishing-api, unless overridden by the publishing application.",
      "type": "string",
      "format": "date-time"
    },
    "frontend_links_with_base_path": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "base_path",
          "content_id",
          "title"
        ],
        "additionalProperties": true,
        "properties": {
          "api_path": {
            "$ref": "#/definitions/absolute_path"
          },
          "base_path": {
            "$ref": "#/definitions/absolute_path"
          },
          "content_id": {
            "$ref": "#/definitions/guid"
          },
          "document_type": {
            "type": "string"
          },
          "links": {
            "type": "object",
            "patternProperties": {
              "^[a-z_]+$": {
                "$ref": "#/definitions/frontend_links_with_base_path"
              }
            }
          },
          "public_updated_at": {
            "oneOf": [
              {
                "$ref": "#/definitions/public_updated_at"
              },
              {
                "type": "null"
              }
            ]
          },
          "schema_name": {
            "type": "string"
          },
          "title": {
            "type": "string"
          }
        }
      }
    },
    "guid": {
      "type": "string",
      "pattern": "^[a-f0-9]{8}-[a-f0-9]{4}-[1-5][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$"
    },
    "public_updated_at": {
      "description": "When the content was last significantly changed (a major update). Shown to users.  Automatically determined by the publishing-api, unless overridden by the publishing application.",
      "type": "string",
      "format": "date-time"
    },
    "publishing_app_name": {
      "description": "The application that published this item.",
      "type": "string",
      "enum": [
        "organisations-publisher",
        "publisher"
      ]
    },
    "publishing_request_id": {
      "description": "A unique identifier used to track publishing requests to rendered content",
      "oneOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ]
    },
    "rendering_app": {
      "description": "The application that renders this item.",
      "type": "string",
      "enum": [
        "collections-frontend",
        "frontend"
      ]
    },
    "title": {
      "type": "string"
    },
    "withdrawn_notice": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "explanation": {
          "type": "string"
        },
        "withdrawn_at": {
          "format": "date-time"
        }
      }
    }
  }
}

=== publishing-platform/publishing-api/content_schemas/examples/organisation/frontend/organisation.json
{
  "base_path": "/organisations/digital-services",
  "content_id": "af07d5a5-df63-4ddc-9383-6a666845ebe9",
  "description": null,
  "details": {
    "abbreviation": "DS",
    "organisation_type": "department",
    "status": "live"
  },
  "document_type": "organisation",
  "first_published_at": "2025-02-13T09:13:45Z",
  "links": {
    "primary_publishing_organisation": [
      {
        "api_path": "/api/content/organisations/digital-services",
        "api_url": "http://www.dev.publishing-platform.co.uk/api/content/organisations/digital-services",
        "base_path": "/organisations/digital-services",
        "content_id": "af07d5a5-df63-4ddc-9383-6a666845ebe9",
        "details": {
          "abbreviation": "DS",
          "status": "live"
        },
        "document_type": "organisation",
        "links": {

        },
        "schema_name": "organisation",
        "title": "Digital Services",
        "web_url": "http://www.dev.publishing-platform.co.uk/organisations/digital-services",
        "withdrawn": false
      }
    ]
  },
  "phase": "live",
  "public_updated_at": "2025-03-24T21:40:24Z",
  "publishing_app": "organisations-publisher",
  "publishing_request_id": "30073-1588319891.535-10.13.4.55-540",
  "rendering_app": "collections-frontend",
  "schema_name": "organisation",
  "title": "Digital Services",
  "updated_at": "2025-04-02T15:27:16Z",
  "withdrawn_notice": {

  }
}
