=== publishing-platform/publishing-api/content_schemas/dist/formats/homepage/publisher/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "required": [
    "base_path",
    "details",
    "document_type",
    "publishing_app",
    "rendering_app",
    "routes",
    "schema_name",
    "title",
    "update_type"
  ],
  "additionalProperties": false,
  "properties": {
    "auth_bypass_ids": {
      "description": "A list of ids that will allow access to this item for non-authenticated users",
      "$ref": "#/definitions/guid_list"
    },
    "base_path": {
      "$ref": "#/definitions/absolute_path"
    },
    "change_note": {
      "type": [
        "null",
        "string"
      ]
    },
    "description": {
      "$ref": "#/definitions/description_optional"
    },
    "details": {
      "$ref": "#/definitions/details"
    },
    "document_type": {
      "type": "string",
      "enum": [
        "homepage"
      ]
    },
    "first_published_at": {
      "$ref": "#/definitions/first_published_at"
    },
    "last_edited_at": {
      "description": "Last time when the content received a major or minor update.",
      "type": "string",
      "format": "date-time"
    },
    "links": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
      }
    },
    "phase": {
      "description": "The service design phase of this content item",
      "type": "string",
      "enum": [
        "alpha",
        "beta",
        "live"
      ]
    },
    "previous_version": {
      "type": "string"
    },
    "public_updated_at": {
      "$ref": "#/definitions/public_updated_at"
    },
    "publishing_app": {
      "$ref": "#/definitions/publishing_app_name"
    },
    "redirects": {
      "type": "array",
      "additionalItems": false,
      "items": {
      }
    },
    "rendering_app": {
      "$ref": "#/definitions/rendering_app"
    },
    "routes": {
      "$ref": "#/definitions/routes"
    },
    "schema_name": {
      "type": "string",
      "enum": [
        "homepage"
      ]
    },
    "title": {
      "$ref": "#/definitions/title"
    },
    "update_type": {
      "$ref": "#/definitions/update_type"
    }
  },
  "definitions": {
    "description": {
      "type": "string"
    },
    "absolute_path": {
      "description": "A path only. Query string and/or fragment are not allowed.",
      "type": "string",
      "pattern": "^/(([a-zA-Z0-9._~!$&'()*+,;=:@-]|%[0-9a-fA-F]{2})+(/([a-zA-Z0-9._~!$&'()*+,;=:@-]|%[0-9a-fA-F]{2})*)*)?$"
    },
    "description_optional": {
      "anyOf": [
        {
          "$ref": "#/definitions/description"
        },
        {
          "type": "null"
        }
      ]
    },
    "details": {
      "type": "object",
      "properties": {
      }
    },
    "first_published_at": {
      "description": "The date the content was first published.  Automatically determined by the publishing-api, unless overridden by the publishing application.",
      "type": "string",
      "format": "date-time"
    },
    "guid": {
      "type": "string",
      "pattern": "^[a-f0-9]{8}-[a-f0-9]{4}-[1-5][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$"
    },
    "guid_list": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/guid"
      },
      "uniqueItems": true
    },
    "public_updated_at": {
      "description": "When the content was last significantly changed (a major update). Shown to users.  Automatically determined by the publishing-api, unless overridden by the publishing application.",
      "type": "string",
      "format": "date-time"
    },
    "publishing_app_name": {
      "description": "The application that published this item.",
      "type": "string",
      "enum": [
        "organisations-publisher",
        "publisher",
        "publishing-api"
      ]
    },
    "rendering_app": {
      "description": "The application that renders this item.",
      "type": "string",
      "enum": [
        "collections-frontend",
        "content-store",
        "frontend"
      ]
    },
    "route": {
      "type": "object",
      "required": [
        "path",
        "type"
      ],
      "additionalProperties": false,
      "properties": {
        "path": {
          "type": "string"
        },
        "type": {
          "enum": [
            "prefix",
            "exact"
          ]
        }
      }
    },
    "routes": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/route"
      },
      "minItems": 1
    },
    "title": {
      "type": "string"
    },
    "update_type": {
      "enum": [
        "major",
        "minor",
        "republish"
      ]
    }
  }
}

=== publishing-platform/publishing-api/content_schemas/examples/homepage/publisher/homepage.json
{
  "base_path": "/",
  "document_type": "homepage",
  "schema_name": "homepage",
  "title": "Publishing Platform homepage",
  "description": "",
  "details": {
  },
  "routes": [
    {
      "path": "/",
      "type": "exact"
    }
  ],
  "publishing_app": "publishing-api",
  "rendering_app": "frontend",
  "public_updated_at": "2015-07-30T13:58:11+00:00",
  "update_type": "major"
}
