=== publishing-platform/publishing-api/content_schemas/dist/formats/redirect/publisher/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "required": [
    "base_path",
    "document_type",
    "publishing_app",
    "redirects",
    "schema_name",
    "update_type"
  ],
  "additionalProperties": false,
  "properties": {
    "auth_bypass_ids": {
      "description": "A list of ids that will allow access to this item for non-authenticated users",
      "$ref": "#/definitions/guid_list"
    },
    "base_path": {
      "$ref": "#/definitions/absolute_path"
    },
    "change_note": {
      "type": [
        "null",
        "string"
      ]
    },
    "description": {
      "type": "null"
    },
    "details": {
      "type": "object",
      "additionalProperties": false,
      "properties": {}
    },
    "document_type": {
      "type": "string",
      "enum": [
        "redirect"
      ]
    },
    "first_published_at": {
      "$ref": "#/definitions/first_published_at"
    },
    "last_edited_at": {
      "description": "Last time when the content received a major or minor update.",
      "type": "string",
      "format": "date-time"
    },
    "links": {
      "type": "object",
      "additionalProperties": false,
      "properties": {}
    },
    "phase": {
      "description": "The service design phase of this content item",
      "type": "string",
      "enum": [
        "alpha",
        "beta",
        "live"
      ]
    },
    "previous_version": {
      "type": "string"
    },
    "public_updated_at": {
      "$ref": "#/definitions/public_updated_at"
    },
    "publishing_app": {
      "$ref": "#/definitions/publishing_app_name"
    },
    "redirects": {
      "$ref": "#/definitions/redirects"
    },
    "rendering_app": {
      "type": "null"
    },
    "routes": {
      "type": "array",
      "additionalItems": false,
      "items": {}
    },
    "schema_name": {
      "type": "string",
      "enum": [
        "redirect"
      ]
    },
    "title": {
      "type": "null"
    },
    "update_type": {
      "$ref": "#/definitions/update_type"
    }
  },
  "definitions": {
    "absolute_path": {
      "description": "A path only. Query string and/or fragment are not allowed.",
      "type": "string",
      "pattern": "^/(([a-zA-Z0-9._~!$&'()*+,;=:@-]|%[0-9a-fA-F]{2})+(/([a-zA-Z0-9._~!$&'()*+,;=:@-]|%[0-9a-fA-F]{2})*)*)?$"
    },
    "first_published_at": {
      "description": "The date the content was first published.  Automatically determined by the publishing-api, unless overridden by the publishing application.",
      "type": "string",
      "format": "date-time"
    },
    "guid": {
      "type": "string",
      "pattern": "^[a-f0-9]{8}-[a-f0-9]{4}-[1-5][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$"
    },
    "guid_list": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/guid"
      },
      "uniqueItems": true
    },
    "public_updated_at": {
      "description": "When the content was last significantly changed (a major update). Shown to users.  Automatically determined by the publishing-api, unless overridden by the publishing application.",
      "type": "string",
      "format": "date-time"
    },
    "publishing_app_name": {
      "description": "The application that published this item.",
      "type": "string",
      "enum": [
        "content-publisher",
        "organisations-publisher",
        "publisher",
        "publishing-api"
      ]
    },
    "redirect_route": {
      "type": "object",
      "required": [
        "path",
        "type",
        "destination"
      ],
      "additionalProperties": false,
      "properties": {
        "destination": {
          "type": "string",
          "format": "uri"
        },
        "path": {
          "$ref": "#/definitions/absolute_path"
        },
        "segments_mode": {
          "description": "For prefix redirects, preserve or ignore the rest of the fullpath. For exact, preserve or ignore the querystring.",
          "enum": [
            "preserve",
            "ignore"
          ]
        },
        "type": {
          "enum": [
            "prefix",
            "exact"
          ]
        }
      }
    },
    "redirects": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/redirect_route"
      },
      "minItems": 1
    },
    "update_type": {
      "enum": [
        "major",
        "minor",
        "republish"
      ]
    }
  }
}

=== publishing-platform/publishing-api/content_schemas/examples/redirect/publisher/redirect.json
{
  "base_path": "/test-redirect",
  "publishing_app": "publisher",
  "public_updated_at": "2024-08-28T16:21:11Z",
  "redirects": [
    {
      "path": "/test-redirect",
      "type": "exact",
      "destination": "/test-redirected?query=answer#fragment"
    }
  ],
  "document_type": "redirect",
  "schema_name": "redirect",
  "update_type": "major"
}
